#page title
page_title                                : DailyRetro 

# App Info
ios_app_id                                : 1605680196 
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : assets/presskit.zip  
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/AppIcon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Summarize your day! DailyRetro is your all-in-one solution for daily productivity and self-reflection.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Information About Yourself
your_name                                 : "Liqiang W"
your_link                                 : https://apps.apple.com/us/app/dailyretro/id1605680196 
your_city                                 : 
email_address                             : dailyretro.app@gmail.com
facebook_username                         : dailyretroapp 
instagram_username                        : 
twitter_username                          :
github_username                           :
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Diary keeping
    description                           : Easily write and capture your thoughts, memories, and photos with markdown formatting.
    fontawesome_icon_name                 : magic
    
  - title                                 : Habit tracking 
    description                           : Stay organized and build positive habits while breaking bad ones.
    fontawesome_icon_name                 : dumbbell 

  - title                                 : Daily reminders 
    description                           : Get timely nudges and notifications to stay focused and productive throughout the day. 
    fontawesome_icon_name                 : envelope 

  - title                                 : Passcode support 
    description                           : Keep your diary and habit data secure with passcode protection. 
    fontawesome_icon_name                 : lock

  - title                                 : iCloud support 
    description                           : Safely backup and access your diary and habit data across multiple devices. 
    fontawesome_icon_name                 : cloud
  

# Theme Settings
topbar_color                              : "#002D59"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#66CCFF"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
